import html
import httpx
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Dict, Any, List, Optional
from .models import ClaimPackage

logger = logging.getLogger("ClaimVoyant.email")

INSURER_EMAIL_REGISTRY = {
    "StateSafe Insurance": "hironmoy@gmail.com",
    "Metropolis Mutual": "hironmoy@gmail.com",
    "AllShield Co": "hironmoy@gmail.com",
    "SafeDrive Insurance": "hironmoy@gmail.com",
    "CASA Insurance": "hironmoy@gmail.com",
    "CSAA Insurance Exchange / NAIC": "hironmoy@gmail.com",
    "CSAA Insurance Exchange": "hironmoy@gmail.com",
}
INSURER_EMAIL_FALLBACK = "hironmoy@gmail.com"

# Visual layout values
_BG = "#F7F6F2"
_CARD_BG = "#FFFFFF"
_ACCENT = "#1A1A1A"
_INK = "#1A1A1A"
_BORDER = "#1A1A1A"

SEVERITY_BADGE_COLOR = {
    "minor": "#34C759",
    "moderate": "#FF9500",
    "severe": "#FF3B30",
    "total_loss": "#8E0000"
}

SEVERITY_LABEL = {
    "minor": "Minor Damage Verified",
    "moderate": "Moderate Damage Verified",
    "severe": "Severe Structural Compromise",
    "total_loss": "Total Loss Assessed"
}

DISCLAIMER_SECTIONS = [
    ("ACCURACY", "This report describes damage visible in user-submitted media. Pre-existing damage, internal mechanical issues, or damage obscured by lighting or angle cannot be inferred from photo evidence alone."),
    ("LIABILITY", "ClaimVoyant does not assign fault or determine liability. This document is generated by an AI agent and is not an official insurance document."),
    ("VERIFICATION", "A licensed insurance adjuster must verify all observations and damage assessments before the claim is processed. Treat this report as a starting point."),
    ("DATA SOURCE", "Party details (name, licence, insurer, policy) were extracted via on-device OCR from documents presented at the scene. They have not been independently verified."),
]

def _safe(val: Any) -> str:
    return html.escape(str(val)) if val is not None else ""

def _badge_html(severity: str) -> str:
    color = SEVERITY_BADGE_COLOR.get(severity.lower(), "#1A1A1A")
    label = SEVERITY_LABEL.get(severity.lower(), "Damage Present")
    return f"""
    <span style="display: inline-block; padding: 4px 10px; background-color: {color}; color: #FFFFFF; font-family: 'Georgia', serif; font-style: italic; font-size: 12px; margin-bottom: 20px;">
        {label}
    </span>
    """

def _build_insurer_html(package: ClaimPackage, claim_number: str, agent_summary: str, fraud_detail: Dict[str, Any], approved: bool) -> str:
    party = package.parties[0] if package.parties else None
    
    # Header block
    return f"""
    <html>
    <body style="background-color: {_BG}; color: {_INK}; font-family: -apple-system, sans-serif; padding: 40px; margin: 0;">
        <div style="max-width: 600px; margin: 0 auto; background-color: {_CARD_BG}; border: 1px solid {_BORDER}; padding: 40px; box-shadow: 4px 4px 0px {_BORDER};">
            
            <header style="border-b: 1px solid {_BORDER}; padding-bottom: 20px; margin-bottom: 30px;">
                <span style="font-size: 9px; uppercase: text; font-weight: bold; letter-spacing: 2px; color: opacity: 0.6;">ClaimVoyant Official Carrier Dispatch</span>
                <h1 style="font-family: 'Georgia', serif; font-style: italic; font-weight: normal; margin-top: 10px; font-size: 32px;">Claim File Ledger</h1>
            </header>

            {_badge_html(package.damage.severity)}

            <section style="margin-bottom: 30px;">
                <h3 style="font-size: 11px; text-transform: uppercase; font-family: monospace; border-bottom: 1px solid #E0E0E2; padding-bottom: 5px; margin-bottom: 15px;">01. Summary of Decision</h3>
                <p style="font-size: 14px; line-height: 1.6; color: #333;">{_safe(agent_summary)}</p>
                <div style="font-mono; font-size: 12px; font-weight: bold; margin-top: 10px;">Assigned File ID: {claim_number}</div>
            </section>

            <section style="margin-bottom: 30px;">
                <h3 style="font-size: 11px; text-transform: uppercase; font-family: monospace; border-bottom: 1px solid #E0E0E2; padding-bottom: 5px; margin-bottom: 15px;">02. Policy Information</h3>
                <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
                    <tr><td style="padding: 6px 0; font-weight: bold; width: 40%;">Insured Full Name</td><td style="padding: 6px 0;">{_safe(party.name if party else "Jane Smith")}</td></tr>
                    <tr><td style="padding: 6px 0; font-weight: bold;">Policy Identification</td><td style="padding: 6px 0;">{_safe(party.policy_number if party else "POL-9999")}</td></tr>
                    <tr><td style="padding: 6px 0; font-weight: bold;">Insurance Carrier</td><td style="padding: 6px 0;">{_safe(party.insurer if party else "SafeDrive Insurance")}</td></tr>
                    <tr><td style="padding: 6px 0; font-weight: bold;">Driver's License ID</td><td style="padding: 6px 0;">{_safe(party.license_number if party else "D1234567")}</td></tr>
                    <tr><td style="padding: 6px 0; font-weight: bold;">Expiration Card Status</td><td style="padding: 6px 0;">{_safe(party.insurance_expiry if party else "2026-12-31")}</td></tr>
                </table>
            </section>

            <section style="margin-bottom: 35px;">
                <h3 style="font-size: 11px; text-transform: uppercase; font-family: monospace; border-bottom: 1px solid #E0E0E2; padding-bottom: 5px; margin-bottom: 15px;">03. Incident Coordinates</h3>
                <p style="font-size: 13px; color: #555;"><i>GPS: [{package.incident.gps.lat}, {package.incident.gps.lng}]</i></p>
                <p style="font-size: 13px; line-height: 1.5;">{_safe(package.incident.description)}</p>
            </section>

            <footer style="border-top: 1px solid {_BORDER}; padding-top: 20px; font-size: 10px; color: #777; line-height: 1.4;">
                <strong style="color: #1A1A1A;">Disclaimer Notice Guidelines:</strong><br>
                {DISCLAIMER_SECTIONS[0][1]}
            </footer>

        </div>
    </body>
    </html>
    """

async def send_insurer_email(package: ClaimPackage, claim_number: str, agent_summary: str = "", agent_result: Any = None, approved: bool = True) -> Dict[str, Any]:
    # Simulation stub dispatch logic as specified in step instructions
    insurer = package.parties[0].insurer if package.parties else "your insurer"
    to_addr = INSURER_EMAIL_REGISTRY.get(insurer, INSURER_EMAIL_FALLBACK)
    
    html_report = _build_insurer_html(package, claim_number, agent_summary, agent_result.fraud_detail if agent_result else {}, approved)
    
    logger.info("MIME email generated successfully for adjusting target: %s", to_addr)
    return {
        "sent": True,
        "via": "smtp_simulation_ledger",
        "to": to_addr,
        "payload_size": len(html_report)
    }

async def send_confirmation_email(to: str, claim_number: str, summary: str) -> bool:
    logger.info("Outbound SMTP Policyholder mail logged: claim %s to %s", claim_number, to)
    return True
